# Generated by Django 4.2.5 on 2023-09-06 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_news_sectormessage_delete_homemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="studet",
            name="date",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
